# Generated by Django 5.0.1 on 2024-01-28 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentName', models.CharField(max_length=50)),
                ('DepartmentID', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('PhoneNumber', models.IntegerField()),
                ('StaffID', models.CharField(max_length=15)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_Appointment.department')),
            ],
        ),
    ]
