# Generated by Django 5.0.1 on 2024-01-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='StaffID',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
