# Generated by Django 5.0.1 on 2024-01-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Appointment', '0002_alter_doctor_staffid_alter_doctor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('PhoneNumber', models.IntegerField()),
                ('Patient_IDNumber', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='StaffID',
            new_name='Doctor_StaffID',
        ),
    ]
