# Generated by Django 5.0.1 on 2024-03-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Drycleaning Only', 'Drycleaning Only'), ('Ironing', 'Drycleaning and ironing'), ('House cleaning', 'House cleaning'), ('Shoe laundry', 'Shoe laundry')], max_length=50)),
            ],
        ),
    ]
