# Generated by Django 5.0.1 on 2024-03-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryservice',
            name='service',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
