# Generated by Django 5.0.1 on 2024-04-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_laundryservice_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundryservice',
            name='service',
        ),
        migrations.AddField(
            model_name='laundryservice',
            name='duvet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laundryservice',
            name='personal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laundryservice',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='laundryservice',
            name='shoes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laundryservice',
            name='shorts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laundryservice',
            name='sweaters',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laundryservice',
            name='trousers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laundryservice',
            name='tshirts',
            field=models.IntegerField(null=True),
        ),
    ]
